### ISSUE TITLE
np.bool_ in vcf.gt_bases gives DepracationWarning

### ISSUE THREAD

**Issue by envanloo** [brentp/cyvcf2#193] opened 2021-03-08 16:29 UTC
WIth a bcf file coming from bwa mem read mapping and bcftools mpileup variant calling I get the following error on the use of vcf.gt_bases:

DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
Out[48]: array(['G/G', 'G/A', 'G/G', 'G/G', 'G/G', 'G/G'], dtype='<U3')

It is seen (Python 3.7) as a numpy array with numpy.str_ elements (e.g. with content 'G/G' as an example of an element). Just printing the whole arrary or an element gives the same error.

This feels like cyvcf2 could start to break any moment the Python 3 community would decide not to allow this any longer.

**Comment by brentp** [comment] 2021-03-08 17:17
can you show how you get this error? I do this:

```
n [1]: import cyvcf2

In [2]: cyvcf2.__version__
Out[2]: '0.30.4'

In [3]: v = cyvcf2.VCF("cyvcf2/tests/test.vcf.gz")

In [4]: variant = next(v)

In [5]: variant.gt_bases
array(['CCCTAA/CCCTAA', './.', './.', './.', './.', 'CCCTAA/CCCTAA',
       './.', './.', './.', './.', 'CCCTAA/CCCTAA', 'CCCTAA/CCCTAA',
       'CCCTAA/CCCTAA', './.', './.', 'CCCTAA/CCCTAA', 'CCCTAA/CCCTAA',
       './.', './.', './.', 'CCCTAA/CCCTAA', './.', './.', './.', './.',
       './.', './.', './.', './.', 'CCCTAA/CCCTAA', 'CCCTAA/CCCTAA' ...

In [7]: import sys

In [8]: sys.version
Out[8]: '3.7.8 | packaged by conda-forge | (default, Nov 17 2020, 23:45:15) \n[GCC 7.5.0]'

```

**Comment by grahamgower** [comment] 2021-12-07 10:32
Duplicate of #132, and looks like its been fixed.

**Closed by grahamgower** 2021-12-07 10:32 UTC
